include:
  - board: seeeduino_xiao_ble
    shield: Crypto_left  # Must have a capital 'C' to match your folder
  - board: seeeduino_xiao_ble
    shield: Crypto_right # Must have a capital 'C' to match your folder
  - board: seeeduino_xiao_ble
    shield: settings_reset
